---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-hello
  name: grpc-hello
spec:
  ports:
    - name: grpc-port
      port: 8000
      protocol: TCP
  selector:
    app: grpc-hello
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: grpc-hello
    version: v1
  name: grpc-hello-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-hello
      version: v1
  template:
    metadata:
      labels:
        app: grpc-hello
        version: v1
    spec:
      containers:
      - image: zhongfox/hello:v1
        imagePullPolicy: Always
        name: grpc-hello
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: SERVICE
          value: grpc-hello
        - name: PROTOCOL
          value: GRPC
        - name: PORT
          value: 8000
---

