---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-hello
  name: http-hello
spec:
  ports:
    - name: http-port
      port: 7000
      protocol: TCP
  selector:
    app: http-hello
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: http-hello
    version: v1
  name: http-hello-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-hello
      version: v1
  template:
    metadata:
      labels:
        app: http-hello
        version: v1
    spec:
      containers:
      - image: zhongfox/hello:v1
        imagePullPolicy: Always
        name: http-hello
        ports:
        - containerPort: 7000
          protocol: TCP
        env:
        - name: SERVICE
          value: http-hello
        - name: PROTOCOL
          value: HTTP
        - name: PORT
          value: 7000
---

